# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the application
FROM node:16-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json for dependency installation
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Prepare the runtime image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy only the build output and node_modules from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Set environment variables (example, replace with actual keys)
ENV NOTION_API_KEY=your_notion_api_key_here

# Expose any necessary ports (if applicable, otherwise remove this line)
# EXPOSE 3000

# Command to run the application
ENTRYPOINT ["node", "build/index.js"]
